# Numpy

## Lesson 1

### Importing numpy to the project

In [124]:
import numpy as np

### Creating numpy array

In [125]:
object = [1, 2, 3, 4]
np.array(object)

array([1, 2, 3, 4])

### Special features

### Getting entities from the array

In [126]:
array_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

array_3d[(1, 1, 1)]


18

### Changing entities in the array

In [127]:
array_3d[(1, 1, 1)] = 777
array_3d[(1, 1, 1)]

777

### Array from exact element

In [128]:
object = [1, 2, 3, 4, 5]
a = np.array(object)
a[[1, 1, 1, 1, 1, 1]]

array([2, 2, 2, 2, 2, 2])

### Boolean array

In [129]:
object = [1, 2, 3, 4, 5]
a = np.array(object)
a[[True, True, False, False, True]]

array([1, 2, 5])

### Reshape function

In [130]:
object = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(object)
a.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Lesson 2

### Array function

In [131]:
some_array = np.array([1, 2, 3, 4, 5]) # Will create an array from a list

some_array1 = np.array((1, 2, 3, 4, 5)) # Will create an array from a tuple

some_array2 = np.array("Hello, World!") # Will create an array of strings from a string

### All data types in Numpy

In [132]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'ulong': numpy.uint64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex12

## Auto-fill functions

##### That`s how it is done without Numpy

In [133]:
np.array([0]*15)

np.array([x for x in range(15)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Empty function

In [134]:
np.empty((2, 4), "int32") # creates an empty mattrix

array([[          0,  1075838976, -1789415188,  1076213536],
       [-2120171215,  1076721893,           0,  1077149696]], dtype=int32)

### Eye function

In [135]:
np.eye(4, 5, 0, "int32") # creates mattrix with 1 on the main diagonal

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int32)

### Identity function

In [136]:
np.identity(8, "int32") # creates square mattrix with 1 on the main diagonal

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

### Ones function

In [137]:
np.ones((8, 9), "int32") # creates  mattrix with 1 in all values

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

### Zeros function

In [138]:
np.zeros((8, 9), "int32") # creates mattrix with 0 in all the values

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

### Full function

In [139]:
np.full((3, 3), 777, "int32") # creates mattrix with 0 in all the values

array([[777, 777, 777],
       [777, 777, 777],
       [777, 777, 777]], dtype=int32)

## Mattrix creators

### mat function

In [140]:
np.mat('1 2 3 4') # creates mattrix from given values 1x4
np.mat('1, 2, 3, 4') # 1x4
np.mat('1, 2; 3, 4') # 2x4

matrix([[1, 2],
        [3, 4]])

### diag function

In [141]:
np.diag([1, 2, 3, 4])
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

### diagflat function

In [142]:
np.diagflat([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

### tri function

In [143]:
np.tri(4, 6)

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### tril function

In [144]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

### triu function

In [145]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### vander function

In [146]:

np.vander([1, 2, 3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

## Numeric diapasons

### arange function

In [147]:
np.arcange(8)

AttributeError: module 'numpy' has no attribute 'arcange'

### linspace function

In [ ]:
np.linspace(8, 20)

array([ 8. ,  9.2, 10.4, 11.6, 12.8, 14. , 15.2, 16.4, 17.6, 18.8, 20. ])

### logspace function

In [ ]:
np.logspace(8, 20, 4)

array([1.e+08, 1.e+12, 1.e+16, 1.e+20])

### geomspace function

In [ ]:
np.geomspace(8, 20, 4)

array([ 8.        , 10.85767047, 14.73612599, 20.        ])

## Copying arrays

### copy

In [ ]:
a = np.array([range(10)])
b = np.copy(a)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### fromfunction

In [ ]:
a = np.array([range(10)])

def getRange(x, y):
    return 100*x + y

np.fromfunction(getRange, (2, 2))

array([[  0.,   1.],
       [100., 101.]])

### fromiter

In [ ]:
np.fromiter("Hello", dtype="U1")

array(['H', 'e', 'l', 'l', 'o'], dtype='<U1')

### fromstring

In [ ]:
np.fromstring("1;1;3", dtype="int32", sep=";")

array([1, 1, 3], dtype=int32)

## Array properties

### dtype

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a.dtype # returns data type of the array
a.dtype = np.float32 # changing data type property

dtype('int64')

### itemsize

In [ ]:
a.itemsize # returns the size of an array element

8

### ndim

In [ ]:
b = np.zeros((3, 3, 3, 4))
b.ndim # returns the dimentions of an array

3

### size

In [ ]:
b = np.zeros((3, 3, 3, 4))
b.size # returns the quanity of elements of the array

108

### shape

In [ ]:
b = np.zeros((3, 3, 3, 4))
b.shape # returns the shape of an array
b.shape = (4, 3, 3, 3)

In [ ]:
b = np.arange(100)
b.shape = -1, 5, 4 # the first parameter will be chosen automatically
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

### reshape

In [ ]:
b = np.zeros((3, 3, 3, 4))
c = b.reshape(1, 108)
"""
    b and c are still linked to the same array
"""

### transponate

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
d = b.T
"""
    b and d are still linked to the same data
"""
d[1] = 777
b

array([[  0, 777,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 777,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 777,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 777,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 777,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 777,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 777,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 777,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 777,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 777,  92,  93,  94,  95,  96,  97,  98,  99]])

### view()

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
c = b.T
"""
    c is linked to b directly
"""
c = b.view()
"""
    now c is linked to b`s data, but not to the b presentation directly
"""

array([[  0, 777,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 777,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 777,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 777,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 777,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 777,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 777,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 777,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 777,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 777,  92,  93,  94,  95,  96,  97,  98,  99]])

### copying an array`s data

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
c = np.array(b)
"""
    now c is not connected to b at all
"""

d = b.copy() #another way to create a copy

array([[  0, 777,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 777,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 777,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 777,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 777,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 777,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 777,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 777,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 777,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 777,  92,  93,  94,  95,  96,  97,  98,  99]])

### ravel

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
b.ravel() # turning matrix into vector
b.shape = 10, 10
b.shape = -1 # The same result

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### resize

In [ ]:
b = np.arange((100))
b.resize(10, 10)
# This method does not return any values but changes the presentation of an array itself

b.resize(9, 9) # notice, that the number of elements is reduced
b.resize(100, 100) # notice, that the number of elements is increased
b

array([[0, 1, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### expand_dims

In [ ]:
b = np.arange((100)).reshape(10, 10)
b = np.expand_dims(b, axis=0)
# a new axis is added to b
b = np.expand_dims(b, axis=-1)
# adds a new axis to the end of the array


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

### append and delete

In [170]:
b = np.arange((100)).reshape(10, 10)
b = np.append(b, [[1, 2, 3, 777, 777, 777, 777, 777, 777, 777]], axis=0)
b = np.delete(b, 0, axis=0)
b

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [  1,   2,   3, 777, 777, 777, 777, 777, 777, 777]])